Export data into csv
Gilles-Maurer-Organization/AI50_patrolling pull request #105
Opened 2024-12-22 15:07 UTC by Eileenj57

This pull request introduces several changes to the `controllers` and `services` modules to enhance the simulation's idleness data management and export functionality. The most important changes include modifications to the `IdlenessController`, `SimulationController`, and `CSVService` to support exporting idleness data at regular intervals.

Enhancements to idleness data management:

* [`controllers/IdlenessesController.py`](diffhunk://#diff-c2bef98ad20b10e40bc8de7b6d5d9c37712f9da10084773e0fc3ce15e767cef0L13-R22): Renamed `_idleness` to `idleness` and added a reference to `SimulationDataController`. Updated `draw_idlenesses` method to use the new `idleness` attribute and set the `idleness_data_provider` in `SimulationDataController`. [[1]](diffhunk://#diff-c2bef98ad20b10e40bc8de7b6d5d9c37712f9da10084773e0fc3ce15e767cef0L13-R22) [[2]](diffhunk://#diff-c2bef98ad20b10e40bc8de7b6d5d9c37712f9da10084773e0fc3ce15e767cef0L34-R40)

* [`controllers/SimulationController.py`](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbR2-R10): Added `SimulationDataController` and `CSVService` as dependencies. Introduced the `start_idleness_export` method to export idleness data every 10 seconds with metadata. Updated `set_simulation_started` to initialize idleness export when the simulation starts. [[1]](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbR2-R10) [[2]](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbL21-R35) [[3]](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbL36-R70) [[4]](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbR121-R123) [[5]](diffhunk://#diff-82c5961327806d4c85230272948e0b08c417b18a4507ee001124754c634e0dfbR133-R154)

Enhancements to CSV service:

* [`services/CSVService.py`](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62L1-R14): Added methods to manage test numbers and extract graph numbers from file paths. Introduced `export_idleness_data` function to handle periodic idleness data export. [[1]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62L1-R14) [[2]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R26) [[3]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R37-R42) [[4]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R55-R62) [[5]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R208) [[6]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R355) [[7]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R380-R401) [[8]](diffhunk://#diff-a00adcc39282126a4e78c15b22e45eae5e75a519f77c0d141f7c845487e1cf62R417-R519)

Controller initialization updates:

* [`controllers/ViewController.py`](diffhunk://#diff-722f4856660d5df2af5ed4d42f05273d283fcbe62c932dd72bde5506ea738461R49-R55): Updated to initialize `SimulationDataController` and pass it to `SimulationController`. [[1]](diffhunk://#diff-722f4856660d5df2af5ed4d42f05273d283fcbe62c932dd72bde5506ea738461R49-R55) [[2]](diffhunk://#diff-722f4856660d5df2af5ed4d42f05273d283fcbe62c932dd72bde5506ea738461L62-L64)

Start button logic update:

* [`controllers/buttons/StartButtonController.py`](diffhunk://#diff-5de9ef43d637012ca38165f7bdd8a863b2835fc33dd27eabd7aebc1c5d50f2a1L138-R143): Modified to pass the selected algorithm name when starting the simulation.

2024-12-23 18:05 UTC, DynaTiuM requested changes

2024-12-23 18:05 UTC, DynaTiuM commented on services/CSVService.py
> +    csv_filename = f'graph_{current_csv_number}_results.csv'
Mettre toute cette fonction à l'intérieur de la classe CSVService comme méthode

2024-12-23 18:05 UTC, DynaTiuM commented on services/CSVService.py
> +    write_data()
Pareil, stocker dans la classe CSVService comme méthode

2024-12-23 18:05 UTC, DynaTiuM commented on services/CSVService.py
> +        idleness_data_provider (callable): A function that provides the idleness data as (average, max, all-time max).
72 cols ?

2024-12-24 11:59 UTC, Eileenj57 commented on controllers/IdlenessesController.py
> +        from controllers.SimulationDataController import SimulationDataController
pour eviter les import circulaires

2024-12-27 17:27 UTC, DynaTiuM requested changes

2024-12-27 17:27 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
C'est quoi la différence avec la ligne du dessus ?
On ne peut pas simplement utiliser :
        idleness_data = self.idleness.get_idleness_data()
et donc : 
self._simulation_data_controller.idleness_data_provider = idleness_data ?

2024-12-27 17:27 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        from controllers.SimulationDataController import SimulationDataController
Normalement s'il y a un import circulaire c'est que l'archi n'est pas dingue car un constructeur n'est pas censé être appelé dans un constructeur qui l'appel lui-même, mais on va passer au dessus, j'ai la flemme de voir comment on peut refactoriser ça

2024-12-27 17:27 UTC, DynaTiuM commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Encore une fois je vois pas pourquoi c'est appelé ici sachant que c'est déjà appelé dans l'IdlenessController ligne 35

2024-12-27 18:24 UTC, Eileenj57 commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Pcq sinon ca update pas dans mon csv

2024-12-27 18:26 UTC, Eileenj57 commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
Pas compris

2024-12-27 18:28 UTC, Eileenj57 commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
Y en a un qui appelle la fonction et l'autre qui stocké la fonction

2024-12-28 18:19 UTC, DynaTiuM commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Bah oui mais on n'est pas censé l'appeler deux fois, ça double les opérations pour rien

2024-12-28 18:23 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
Mais elle ne sert plus à rien cette ligne du coup ?

2024-12-28 18:49 UTC, Eileenj57 commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Bah ouais mais jsp 
Sinon ca marche plus mais je peux pas regarder

2024-12-29 18:51 UTC, Eileenj57 commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
bah si je l'appelle dans un autre controller

2024-12-29 19:58 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
Où ?

2024-12-29 19:59 UTC, DynaTiuM commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Bah si ça fonctionne tjrs si on supprime cette ligne

2024-12-29 20:00 UTC, DynaTiuM commented on controllers/SimulationController.py
> +        self._idleness_data.update_idleness(self._graph_controller.graph.nodes)
Ca fonctionnait pas avant car tu réinstanciais un IdlenessData, mais maintenant vu que tu récupère une référence d'un IdlenessData stocké dans un autre controleur, les données sont récupérées en permanence

2024-12-29 20:07 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
Après vérification, la ligne ne sert bel et bien à rien, et du coup peut être supprimée.
L'import from controllers.SimulationDataController import SimulationDataController peut aussi être supprimé du coup, et l'instanciation de self._simulation_data_controller peut être supprimée également.

2024-12-29 20:08 UTC, DynaTiuM commented on controllers/IdlenessesController.py
> +        from controllers.SimulationDataController import SimulationDataController
Supprimer l'import

2024-12-30 09:33 UTC, Eileenj57 commented on controllers/IdlenessesController.py
> +        self._simulation_data_controller.idleness_data_provider = self.idleness.get_idleness_data
il est appele dans le csvservice hein

2024-12-30 14:38 UTC, DynaTiuM approved these changes

2024-12-30 14:38 UTC, merged