Evolutional Algorithm
Gilles-Maurer-Organization/AI50_patrolling pull request #50
Opened 2024-12-10 16:35 UTC by guiguiSCH68

Evolutional Algorithm implementation.

2024-12-10 18:12 UTC, DynaTiuM commented on checkIsolatedNodes.py
> +
Traduire tout en anglais.
Essayer d'écrire les commentaires de méthodes avec une largeur de 72 colonnes max. 79 colonnes max pour les parties de code (convention PEP 8).

cf. https://peps.python.org/pep-0008/#maximum-line-length

2024-12-10 18:13 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +
Adopter la convention Google docstring:
https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html

Retirer les définitions des méthodes ici, garder seulement l'expression des attributs.

Ne pas oublier la convention PEP 8 également.

2024-12-10 18:15 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +        """
Convention PEP8 (72 cols max)
Faire de même pour tous les autres commentaires de méthodes.

2024-12-10 18:18 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def initial_population_generation(self):
Spécifier le type de retour.
`initial_population_generation(self) -> np.ndarray:`

2024-12-10 18:19 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def are_all_nodes_visited(self, individual):
Spécifier le type d'individual et le type de retour.
`def are_all_nodes_visited(self, individual: type) -> type_de_retour:`

2024-12-10 18:20 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def get_real_population_from_indicative_population(self):
De même, spécifier le type de retour

2024-12-10 18:21 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def path_lengths_computing(self, path):
Spécifier le type de la variable path et le type de retour de la méthode (float ici selon la docstring ?).

2024-12-10 18:21 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def mean_node_occurrence_computing(self,individual):
De même, typer l'objet et type de retour.

2024-12-10 18:21 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def mean_path_lengths_computing(self,individual):
De même, typer l'objet et type de retour.

2024-12-10 18:22 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def fitness(self):
De même, typer le retour de la méthode.

2024-12-10 18:22 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def dominates(self, individual_1, individual_2):
De même, typer les objets et type de retour.
Faire de même pour toutes les fonctions du fichier.

2024-12-10 18:25 UTC, DynaTiuM commented on checkIsolatedNodes.py
> +def algo_dfs(matrix, node, visited):
L'algorithme est-il encore utilisé ?
La MAJ du A* s'occupe déjà de vérifier si un noeud est complet. Cette méthode est-elle utilisée quelque part dans ton programme ? Si non, supprimer le fichier.

2024-12-11 14:00 UTC, gilles-maurer reviewed
Très bien, je ne connaissais pas la technique Pareto, ça a l'air pas mal. 
- Petit doute sur la boucle while dans l'initialisation
- je me demande si c'est pas mieux de mettre les taux de croisement / mutation en attributs de la classe ? 
- est-ce qu'on laisse le main ? je pense qu'est c'est mieux de l'enlever mais Raph confirmera

2024-12-11 14:03 UTC, gilles-maurer reviewed
ah oui autre chose pour moi la partie qui reconstruit le chemin complet ne doit pas être ici, c'est une partie commune à tout les algos...

2024-12-11 14:07 UTC, gilles-maurer reviewed
j'ai checké le sonar cloud, je suis d'accord que certaines fonctions sont un peu longues après je ne sais pas si ça vaut la peine de se casser la tête pour ça...

2024-12-11 16:15 UTC, gilles-maurer approved these changes

2024-12-12 07:55 UTC, guiguiSCH68 reviewed
applied the changes

2024-12-12 08:07 UTC, DynaTiuM commented
> Très bien, je ne connaissais pas la technique Pareto, ça a l'air pas mal.
> 
> * Petit doute sur la boucle while dans l'initialisation
> * je me demande si c'est pas mieux de mettre les taux de croisement / mutation en attributs de la classe ?
> * est-ce qu'on laisse le main ? je pense qu'est c'est mieux de l'enlever mais Raph confirmera

Enlever le main en effet, ce serait bien de ne pas l'avoir dans l'historique des commits de la branche dev. Dans tous les cas, il sera récupérable dans l'historique des commits du commit qui a été squash.

2024-12-12 08:30 UTC, DynaTiuM requested changes
Dernières petites modifications

2024-12-12 08:30 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +        -> mutation_rate : the mutating rate used in the Algorithm
Retirer les "->"

2024-12-12 08:30 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def __init__(self, nb_of_generations, nb_agent, individuals_number_per_population, graph_object):
Typer les objets + réduire la largeur. Le mieux c'est de mettre sous ce format pour une meilleur visibilité : 
```python
def __init__(
        self,
        nb_of_generations: int,
        nb_agent: int,
        individuals_number_per_population: int,
        graph_object: ?
    ) -> None:
        self.nb_generations = nb_of_generations
        self.nb_agents = nb_agent
        ....
```

2024-12-12 08:30 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def dominates(self, individual_1: tuple[float, float], individual_2: tuple[float, float]) -> bool:
De même ici, mettre sous le format : 
```python
def dominates(
        self,
        individual_1: tuple[float, float],
        individual_2: tuple[float, float]
    ) -> bool:
```
pour des raisons de visibilité et largeur de code

2024-12-12 08:30 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def selection_with_pareto(self, fitness: list[tuple[float, float]], nb_parent: int) -> np.ndarray:
De même, mettre sous le format comme cité précédemment

2024-12-12 08:30 UTC, DynaTiuM commented on services/algorithms/EvolutionalAlgorithm.py
> +    def vertical_crossing_process(self, parent_1: np.ndarray, parent_2: np.ndarray, nb_crossings: int) -> tuple[
De même pour le format

2024-12-12 08:54 UTC, DynaTiuM approved these changes

2024-12-12 08:58 UTC, merged