Animation management
Gilles-Maurer-Organization/AI50_patrolling pull request #68
Opened 2024-12-13 13:34 UTC by aathane

Link between animation and algorithms

2024-12-13 18:09 UTC, DynaTiuM requested changes

2024-12-13 18:09 UTC, DynaTiuM commented on controllers/SimulationController.py
> +# TODO : Augementer le rayon en fonction de l'oisiveter
Retirer les TODO

2024-12-13 18:09 UTC, DynaTiuM commented on controllers/buttons/StartButtonController.py
>          # TODO: interface for all the algorithm that owns a launch() method,
Retirer le TODO

2024-12-13 18:09 UTC, DynaTiuM commented on controllers/text_boxes/TextBoxController.py
> +    def text_content(self) -> str:
Ajouter la docstring du getter

2024-12-13 18:09 UTC, DynaTiuM commented on models/algorithms/AntColony.py
> +            "Evaporation rate": TextBox(str(evaporation))
Evaporation rate apparait deux fois, le retirer

2024-12-13 18:09 UTC, DynaTiuM commented on models/algorithms/AntColony.py
> +    def initialize_algorithm(self, nb_agents, graph) -> None :
Ecrire la docstring et typer les paramètres

2024-12-13 18:09 UTC, DynaTiuM commented on models/algorithms/Evolutional.py
> +    def initialize_algorithm(self, nb_agents, graph) -> None :
Ecrire la docstring et typer les paramètres

2024-12-13 18:09 UTC, DynaTiuM commented on models/algorithms/KMeans.py
> +    def __init__(self, nb_launch_kmeans=30) -> None:
Typer le paramètre

2024-12-13 18:09 UTC, DynaTiuM commented on models/algorithms/KMeans.py
> +    def initialize_algorithm(self, nb_agents, graph) -> None :
Ecrire la docstring et typer les paramètres

2024-12-13 18:09 UTC, DynaTiuM commented on services/algorithms/AntColonyAlgorithm.py
> +        # List of nodes where an agent can start, IE : 2 agents can't spawn in the same node and an agent can't spawn
72 colonnes ?

2024-12-13 18:09 UTC, DynaTiuM commented on services/algorithms/AntColonyAlgorithm.py
> +    def plot_path_length_history(self, path_length_history):
Typer le paramètre et ajouter le type de retour

2024-12-13 18:09 UTC, DynaTiuM commented on services/algorithms/KMeansAlgorithm.py
> +        #    self._plot(clusters_attribution)
Retirer les commentaires inutiles

2024-12-15 10:48 UTC, DynaTiuM requested changes

2024-12-15 10:48 UTC, DynaTiuM commented on models/algorithms/Evolutional.py
> +        ) -> None :
return un IAlgorithm, le faire pour tous les models qui ont cette méthode.
Ajouter cette méthode en abstract dans la classe IAlgorithmModel

2024-12-15 10:48 UTC, DynaTiuM commented on models/algorithms/KMeans.py
> +        ) -> None :
return un IAlgorithm

2024-12-15 11:53 UTC, DynaTiuM approved these changes

2024-12-15 19:12 UTC, gilles-maurer approved these changes

2024-12-15 19:19 UTC, merged